version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: ai-img-backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    networks:
      - ai-net

  frontend:
     build:
       context: ./frontend
       dockerfile: Dockerfile
       args:
         VITE_API_BASE: http://backend:4000
     ports:
       - "5173:5173"

networks:
  ai-net:
    driver: bridge
